### ISSUE TITLE
Asserion failed.

### ISSUE THREAD

**Issue by marcthenarc** [azarus/TerrainGenerator#2]
Assertion failed: !bPostTickComponentUpdate [File:C:\Users\Marc\Documents\UnrealEngine\Engine\Source\Runtime\Engine\Private\LevelTick.cpp] [Line: 703]   after running in a single direction for a while.  Can't really help otherwise though; it's little over my head. :-)

**Comment by azarus** [comment]
I believe the problem lies in this line:
https://github.com/azarus/TerrainGenerator/blob/master/Source/TerrainGenerator/TerrainGenerationWorker.cpp#L104

Calling this from the worker thread.
MeshComponent->MarkRenderStateDirty();
