### ISSUE TITLE
New terrain system broken

### ISSUE THREAD

**Issue by LaithS** [azarus/TerrainGenerator#6]
The most recent update that switched to the new terrain grid system works way worse than the older one in terms of visual output

**Comment by azarus** [comment]
I am sorry, My original plan was to move this thing to usf but i barely have time for anything else than my other game project. So i uploaded what i had (half done)

**Comment by piroshikin** [comment]
Hi. Which version is works well?
current version is not work in UE4.11 and UE4.13.

**Comment by sch5** [comment]
there are at least 3 minor version of 4.11.x exists (0,1,2) but it should work with any of these, unless the code does not compile. https://github.com/EpicGames/UnrealEngine/releases?after=4.12.0-release 
what's the issue?

**Comment by piroshikin** [comment]
Hi. 
I'm using version 4.11.2. 
procedural field polygons disappear soon when execute project.
I expected this video. https://www.youtube.com/watch?v=e18VIF5xW0k

please see the image.  in windows10 and windows7.

https://drive.google.com/open?id=0B3MAx-rOyxHPV2NwV1hDQXdabHM

**Comment by piroshikin** [comment]
Thanks sch5 ! This is nice advice for me.  I try read source code with ease.
However what behaviour is correct?
I don't know correct behaviour.  Is there video or image?
I want a hint to find a issue.

**Comment by piroshikin** [comment]
I found a little malfunction in the code.
And it look like correctly behaviour in ue 4.12 and 4.13.
thank you.

**Comment by cfr** [comment]
@piroshikin can you please share the fix or at least point where it should be implemented?

**Comment by piroshikin** [comment]
yes! of course!

Source/TerrainGenerator/ProceduralTerrain.cpp
line 104
`+WorkerTask.ChunkLocation= TerrainChunk->ChunkLocation;`
or
`+WorkerTask.ChunkLocation= FVector::ZeroVector;`

WorkerTask.ChunkLocation variable is not initialize data.

**Comment by cfr** [comment]
Thanks @piroshikin!
In case someone wish to get project working with 4.13, here is it: https://github.com/cfr/TerrainGenerator

**Comment by azarus** [comment]
Hey guys,
Sorry for the late reply. I'll look into this as soon as i have a bit more time.
